import Head from "next/head";

import Home from "@components/Home/Home";

export default function Index({ albums }) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Home albums={albums} />
        </div>
    );
}

export async function getServerSideProps() {
    const url = "https://albums-collection-api.herokuapp.com/api/albums";

    const resp = await fetch(`${url}`);
    const albums = await resp.json();

    return {
        props: { albums },
    };
}
